<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251031214404 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE breed_id_breed_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE owner_pet_id_owner_pet_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pet_id_pet_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE species_id_species_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE breed (id_breed INT NOT NULL, name VARCHAR(255) NOT NULL, id_species INT NOT NULL, PRIMARY KEY (id_breed))');
        $this->addSql('CREATE INDEX IDX_F8AF884F7B925E62 ON breed (id_species)');
        $this->addSql('CREATE TABLE public.owner (id_owner INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id_owner))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FEB18718E7927C74 ON public.owner (email)');
        $this->addSql('CREATE TABLE owner_pet (id_owner_pet INT NOT NULL, id_owner INT NOT NULL, id_pet INT NOT NULL, PRIMARY KEY (id_owner_pet))');
        $this->addSql('CREATE INDEX IDX_4B9985CF21E5A74C ON owner_pet (id_owner)');
        $this->addSql('CREATE INDEX IDX_4B9985CF7AF673DF ON owner_pet (id_pet)');
        $this->addSql('CREATE TABLE pet (id_pet INT NOT NULL, name VARCHAR(255) NOT NULL, birth_date DATE NOT NULL, id_breed INT NOT NULL, id_species INT NOT NULL, PRIMARY KEY (id_pet))');
        $this->addSql('CREATE INDEX IDX_E4529B85162AC97F ON pet (id_breed)');
        $this->addSql('CREATE INDEX IDX_E4529B857B925E62 ON pet (id_species)');
        $this->addSql('CREATE TABLE species (id_species INT NOT NULL, name VARCHAR(180) NOT NULL, PRIMARY KEY (id_species))');
        $this->addSql('ALTER TABLE breed ADD CONSTRAINT FK_F8AF884F7B925E62 FOREIGN KEY (id_species) REFERENCES species (id_species) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE owner_pet ADD CONSTRAINT FK_4B9985CF21E5A74C FOREIGN KEY (id_owner) REFERENCES public.owner (id_owner) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE owner_pet ADD CONSTRAINT FK_4B9985CF7AF673DF FOREIGN KEY (id_pet) REFERENCES pet (id_pet) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pet ADD CONSTRAINT FK_E4529B85162AC97F FOREIGN KEY (id_breed) REFERENCES breed (id_breed) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pet ADD CONSTRAINT FK_E4529B857B925E62 FOREIGN KEY (id_species) REFERENCES species (id_species) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE breed_id_breed_seq CASCADE');
        $this->addSql('DROP SEQUENCE owner_pet_id_owner_pet_seq CASCADE');
        $this->addSql('DROP SEQUENCE pet_id_pet_seq CASCADE');
        $this->addSql('DROP SEQUENCE species_id_species_seq CASCADE');
        $this->addSql('ALTER TABLE breed DROP CONSTRAINT FK_F8AF884F7B925E62');
        $this->addSql('ALTER TABLE owner_pet DROP CONSTRAINT FK_4B9985CF21E5A74C');
        $this->addSql('ALTER TABLE owner_pet DROP CONSTRAINT FK_4B9985CF7AF673DF');
        $this->addSql('ALTER TABLE pet DROP CONSTRAINT FK_E4529B85162AC97F');
        $this->addSql('ALTER TABLE pet DROP CONSTRAINT FK_E4529B857B925E62');
        $this->addSql('DROP TABLE breed');
        $this->addSql('DROP TABLE public.owner');
        $this->addSql('DROP TABLE owner_pet');
        $this->addSql('DROP TABLE pet');
        $this->addSql('DROP TABLE species');
    }
}
